### ISSUE TITLE
为什么你们在一年前放弃了这个项目呢？

### ISSUE THREAD

**Issue by Xigong93** [androidflux/androidflux.github.io#13]
我觉得flux 结构要不mvp这种东西，在解决复杂问题的时候，有效的多，比如直播页面，视频播放页面，等等，就是不知道为什么你们放弃了，其实在写出了demo之后，就暂停了。

**Comment by antty** [comment]
flux只是一种思想，不需要具体的架构

**Comment by JiangDaYa0** [comment]
@antty 👍

**Comment by coolfire2015** [comment]
flux是一种思想，但在项目中使用该模式，能简化的时候就简化。我用RxJava2重新实现了RxFlux，并融合Dagger2，Retrofit2，写了新的RxFlux2（有代码模板，方便一键创建）。[RxFlux2](https://github.com/coolfire2015/RxFlux2)，欢迎使用
