### ISSUE TITLE
Actions and the Dispatcher 文档翻译

### ISSUE THREAD

**Issue by ntop001** [androidflux/androidflux.github.io#5]
http://androidflux.github.io/docs/actions-and-the-dispatcher.html#content 的文档翻译，需要提供Android版本的适配（不仅仅是单纯翻译文档）。

**Comment by Damonzh** [comment]
这个有人翻译了吗？

**Comment by JiangDaYa0** [comment]
@Damonzh 我在翻译啊

**Comment by Damonzh** [comment]
@JiangDaYa0 嗷 不过有没有人在翻译 看的不是很清楚呢
